### ISSUE TITLE
Remove unnecessary transpose of linear regression coefficients

### ISSUE THREAD

**Issue by gitgithan** [lewagon/ml-sprint#2]
`pd.concat([pd.DataFrame(features.columns),pd.DataFrame(np.transpose(model.coef_))], axis = 1)`
can be `pd.concat([pd.DataFrame(features.columns),pd.DataFrame(model.coef_)], axis = 1)`

`model.coef_` is a 1d numpy array so transposing doesn't do anything

**Comment by The-Pavel** [comment]
Thanks for opening issues @gitgithan !

Both have been resolved 🙏
