### ISSUE TITLE
Salary prediction

### ISSUE THREAD

**Issue by yuqingwwang** [lewagon/ml-sprint#4]
Hey Pavel,

I'm preparing to teach this workshop and found the model is making very wrong predictions. It works ok in Binder but not in Jupyter Notebook when I run the code locally (I still don't know why).

<img width="528" alt="image" src="https://github.com/The-Pavel/ml_sprint/assets/44486576/47e51d11-bba7-41f9-abee-18db4aacb1be">

I have experimented a bit and found that it can be fixed by using a Ridge model (scaling the X + LinearRegression doesn't work)

<img width="415" alt="image" src="https://github.com/The-Pavel/ml_sprint/assets/44486576/07f2e7a5-8438-44f9-9cf4-cd0a67d0e9cc">

Thank you for your time and please could you let me know if you know why this problem is happening?

**Comment by The-Pavel** [comment]
Hi @yuqingwwang , thanks so much for the issue and investigation!

What machine are you running on locally?

**Comment by yuqingwwang** [comment]
> Hi @yuqingwwang , thanks so much for the issue and investigation!
> 
> What machine are you running on locally?

Thanks for your reply! I am using a MacBook with M1 chip, with scikit-learn==1.1.2

**Comment by davydw** [comment]
@yuqingwwang @The-Pavel , same weird predictions for me.

**Comment by The-Pavel** [comment]
Hi team @davydw @yuqingwwang 

It's a strange issue, seems to be with some underlying computation of coefficients that differs with apple silicon cores vs. intel cores.

However I found that simply **shuffling the CSV** (`salaries.sample(frac=1)`) seems to solve the extreme coefficients

**Comment by yuqingwwang** [comment]
thank you Pavel! I forgot to reply to you here. We delievered the workshop on a Macbook again today and showed our students the gigantic predictions. fyi @AndreiCDanila
